/* Generated by tools/make_decals.py - do not edit.
 * Each decal's rectangle in the atlas, as u0, v0, u1, v1 with v down,
 * and its aspect ratio (width / height). */
#ifndef MR_DECALS_ATLAS_H
#define MR_DECALS_ATLAS_H
#define DECAL_ATLAS_W 2048
#define DECAL_ATLAS_H 1092
#define DECAL_FIN_A 0.382324f, 0.005495f, 0.620605f, 0.357143f, 1.27083f
#define DECAL_FIN_B 0.626465f, 0.005495f, 0.874512f, 0.357143f, 1.32292f
#define DECAL_ENG_R 0.597168f, 0.452381f, 0.846191f, 0.617216f, 2.83333f
#define DECAL_ENG_L 0.002930f, 0.748168f, 0.251953f, 0.913004f, 2.83333f
#define DECAL_ROUNDEL 0.257812f, 0.748168f, 0.345703f, 0.896520f, 1.11111f
#define DECAL_FLAG 0.133789f, 0.923993f, 0.192383f, 0.984432f, 1.81818f
#define DECAL_AN225 0.351562f, 0.748168f, 0.689941f, 0.821429f, 8.66250f
#define DECAL_ICT 0.002930f, 0.452381f, 0.591309f, 0.737179f, 3.87460f
#define DECAL_MRIYA 0.002930f, 0.923993f, 0.127930f, 0.994505f, 3.32468f
#define DECAL_REG 0.695801f, 0.748168f, 0.914062f, 0.820513f, 5.65823f
#define DECAL_CHIN 0.002930f, 0.005495f, 0.376465f, 0.441392f, 1.60714f
#endif
