/* Generated by tools/make_decals.py - do not edit.
 * Each decal's rectangle in the atlas, as u0, v0, u1, v1 with v down,
 * and its aspect ratio (width / height). */
#ifndef MR_DECALS_ATLAS_H
#define MR_DECALS_ATLAS_H
#define DECAL_ATLAS_W 2048
#define DECAL_ATLAS_H 880
#define DECAL_FIN_A 0.002930f, 0.561364f, 0.181641f, 0.888636f, 1.27083f
#define DECAL_FIN_B 0.187500f, 0.561364f, 0.373535f, 0.888636f, 1.32292f
#define DECAL_ENG_R 0.473145f, 0.561364f, 0.597656f, 0.663636f, 2.83333f
#define DECAL_ENG_L 0.603516f, 0.561364f, 0.728027f, 0.663636f, 2.83333f
#define DECAL_ROUNDEL 0.379395f, 0.561364f, 0.467285f, 0.745455f, 1.11111f
#define DECAL_FLAG 0.702148f, 0.902273f, 0.760742f, 0.977273f, 1.81818f
#define DECAL_AN225 0.002930f, 0.902273f, 0.341309f, 0.993182f, 8.66250f
#define DECAL_ICT 0.382324f, 0.006818f, 0.970703f, 0.360227f, 3.87460f
#define DECAL_MRIYA 0.571289f, 0.902273f, 0.696289f, 0.989773f, 3.32468f
#define DECAL_REG 0.347168f, 0.902273f, 0.565430f, 0.992045f, 5.65823f
#define DECAL_CHIN 0.002930f, 0.006818f, 0.376465f, 0.547727f, 1.60714f
#endif
