#include "render.h"
#include "gl_loader.h"
#include "platform.h"
#include "camera.h"
#include <SDL3/SDL.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define STB_IMAGE_WRITE_IMPLEMENTATION
#define STBI_WRITE_NO_STDIO_FAILURE_CHECK
#include "stb_image_write.h"

/* Embedded GLSL (generated by cmake/embed.cmake). */
extern const char shader_common_glsl[], shader_atmosphere_glsl[], shader_terrain_fn_glsl[],
    shader_cloud_fn_glsl[], shader_post_vert[], shader_blit_frag[], shader_blur_frag[],
    shader_bright_frag[], shader_lut_transmittance_frag[], shader_lut_multiscatter_frag[],
    shader_lut_skyview_frag[], shader_lut_aerial_frag[], shader_noise3d_frag[],
    shader_weather_frag[], shader_cloudshadow_frag[], shader_sky_frag[], shader_terrain_vert[],
    shader_terrain_frag[], shader_aircraft_vert[], shader_aircraft_frag[], shader_shadow_frag[],
    shader_clouds_frag[], shader_cloudtaa_frag[], shader_composite_frag[], shader_probe_frag[], shader_precip_vert[],
    shader_precip_frag[], shader_bolt_vert[], shader_bolt_frag[], shader_lights_vert[],
    shader_lights_frag[], shader_lum_frag[], shader_adapt_frag[], shader_final_frag[], shader_present_frag[], shader_msresolve_frag[],
    shader_trail_vert[], shader_trail_frag[];

/* Sizes of things. */
#define TRANS_W 256
#define TRANS_H 64
#define MULTI_N 32
#define SKYVIEW_W 256
#define SKYVIEW_H 128
#define AP_N 32
#define NOISE_BASE 128
#define NOISE_DETAIL 32
#define WEATHER_N 512
#define WEATHER_SIZE 180000.f      /* metres across */
#define CSHADOW_N 512
#define CSHADOW_SIZE 70000.f
#define LUM_N 256
#define RAIN_DROPS 14000
#define BOLT_MAX 160
#define TERRAIN_REACH 480000.f

/* The sun's illuminance outside the atmosphere, in this renderer's units.
 * Everything else is relative to it; the pre-exposure below keeps a moonlit
 * scene and a noon one in the same comfortable range of the float target. */
#define SUN_ILLUM 12.f
#define MOON_FRACTION (1.f / 1500.f)

/* The first reason start-up failed, for the message the user sees. */
static char g_fail[256];
static void render_fail(const char *fmt, const char *what) {
    if (!g_fail[0]) snprintf(g_fail, sizeof g_fail, fmt, what);
}
const char *render_failure(void) { return g_fail[0] ? g_fail : NULL; }

/* ------------------------------------------------------------------------ */
static unsigned compile(GLenum type, const char *const *parts, int n, const char *name) {
    const char *src[16];
    int k = 0;
    src[k++] = "#version 330 core\n";
    for (int i = 0; i < n && k < 16; ++i) src[k++] = parts[i];
    /* MR_DUMP_SHADERS=<folder>: write each shader as the driver gets it, for
     * checking with a strict compiler (glslangValidator) */
    const char *dump = getenv("MR_DUMP_SHADERS");
    if (dump && *dump) {
        char path[512];
        snprintf(path, sizeof path, "%s/%s.%s", dump, name, type == GL_VERTEX_SHADER ? "vert" : "frag");
        FILE *f = fopen(path, "w");
        if (f) { for (int i = 0; i < k; ++i) fputs(src[i], f); fclose(f); }
    }
    unsigned sh = glCreateShader(type);
    glShaderSource(sh, k, src, NULL);
    glCompileShader(sh);
    GLint ok = 0;
    glGetShaderiv(sh, GL_COMPILE_STATUS, &ok);
    char log[4096];
    log[0] = 0;
    glGetShaderInfoLog(sh, sizeof log, NULL, log);
    if (!ok) {
        plat_log("shader %s (%s) failed:\n%s", name, type == GL_VERTEX_SHADER ? "vs" : "fs", log);
        render_fail("The %s shader did not compile on this graphics driver.", name);
        glDeleteShader(sh);
        return 0;
    }
    /* warnings too: what one driver lets pass, a stricter one refuses */
    if (log[0] && log[0] != '\n') plat_log("shader %s (%s) notes:\n%s", name, type == GL_VERTEX_SHADER ? "vs" : "fs", log);
    return sh;
}

unsigned render_program(const char *const *vs, int nvs, const char *const *fs, int nfs, const char *name) {
    unsigned v = compile(GL_VERTEX_SHADER, vs, nvs, name);
    unsigned f = compile(GL_FRAGMENT_SHADER, fs, nfs, name);
    if (!v || !f) return 0;
    unsigned p = glCreateProgram();
    glAttachShader(p, v);
    glAttachShader(p, f);
    glLinkProgram(p);
    glDeleteShader(v);
    glDeleteShader(f);
    GLint ok = 0;
    glGetProgramiv(p, GL_LINK_STATUS, &ok);
    if (!ok) {
        char log[4096];
        glGetProgramInfoLog(p, sizeof log, NULL, log);
        plat_log("program %s failed to link:\n%s", name, log);
        render_fail("The %s shaders did not link on this graphics driver.", name);
        glDeleteProgram(p);
        return 0;
    }
    return p;
}

/* A fullscreen pass: post.vert, then common + the given pieces. */
static unsigned post_program(const char *a, const char *b, const char *c, const char *main_fs, const char *name) {
    const char *vs[] = { shader_common_glsl, shader_post_vert };
    const char *fs[5];
    int n = 0;
    fs[n++] = shader_common_glsl;
    if (a) fs[n++] = a;
    if (b) fs[n++] = b;
    if (c) fs[n++] = c;
    fs[n++] = main_fs;
    return render_program(vs, 2, fs, n, name);
}

/* --- uniforms ------------------------------------------------------------- */
static int loc(unsigned p, const char *n) { return glGetUniformLocation(p, n); }
static void u1f(unsigned p, const char *n, float v) { glUniform1f(loc(p, n), v); }
static void u1i(unsigned p, const char *n, int v) { glUniform1i(loc(p, n), v); }
static void u2f(unsigned p, const char *n, float a, float b) { glUniform2f(loc(p, n), a, b); }
static void u3f(unsigned p, const char *n, float a, float b, float c) { glUniform3f(loc(p, n), a, b, c); }
static void u3v(unsigned p, const char *n, vec3 v) { glUniform3f(loc(p, n), v.x, v.y, v.z); }
static void u4f(unsigned p, const char *n, float a, float b, float c, float d) { glUniform4f(loc(p, n), a, b, c, d); }
static void um4(unsigned p, const char *n, const mat4 *m) { glUniformMatrix4fv(loc(p, n), 1, GL_FALSE, m->m); }
static void um3(unsigned p, const char *n, basis3 b) {
    float m[9] = { b.x.x, b.x.y, b.x.z, b.y.x, b.y.y, b.y.z, b.z.x, b.z.y, b.z.z };
    glUniformMatrix3fv(loc(p, n), 1, GL_FALSE, m);
}
static void tex(unsigned p, const char *n, int unit, GLenum target, unsigned t) {
    glActiveTexture(GL_TEXTURE0 + unit);
    glBindTexture(target, t);
    glUniform1i(loc(p, n), unit);
}
static void draw_fullscreen(void) { glDrawArrays(GL_TRIANGLES, 0, 3); }

/* --- textures and targets ------------------------------------------------- */
static unsigned make_tex2d(int w, int h, GLenum ifmt, GLenum fmt, GLenum type, GLenum filter, GLenum wrap) {
    unsigned t;
    glGenTextures(1, &t);
    glBindTexture(GL_TEXTURE_2D, t);
    glTexImage2D(GL_TEXTURE_2D, 0, ifmt, w, h, 0, fmt, type, NULL);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, filter);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, filter == GL_LINEAR_MIPMAP_LINEAR ? GL_LINEAR : filter);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, wrap);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, wrap);
    return t;
}
static unsigned make_fbo(unsigned color0, unsigned color1) {
    unsigned f;
    glGenFramebuffers(1, &f);
    glBindFramebuffer(GL_FRAMEBUFFER, f);
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, color0, 0);
    if (color1) {
        glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT1, GL_TEXTURE_2D, color1, 0);
        GLenum b[2] = { GL_COLOR_ATTACHMENT0, GL_COLOR_ATTACHMENT1 };
        glDrawBuffers(2, b);
    }
    if (glCheckFramebufferStatus(GL_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE)
        plat_log("framebuffer incomplete");
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    return f;
}
static void del_tex(unsigned *t) { if (*t) { glDeleteTextures(1, t); *t = 0; } }
static void del_fbo(unsigned *f) { if (*f) { glDeleteFramebuffers(1, f); *f = 0; } }

Quality render_quality(int setting) {
    float q = clampf(setting / 100.f, 0.f, 1.f);
    Quality o;
    /* The top two thirds keep the picture sharp (70-100% resolution, full
     * multisampling) and spend the difference on the clouds; the bottom third
     * is for integrated graphics, and gives up resolution and samples too. */
    if (q >= 0.3f) {
        float t = (q - 0.3f) / 0.7f;
        o.scale = lerpf(0.7f, 1.0f, t);
        o.cloud_scale = lerpf(0.45f, 0.6f, t);
        o.cloud_steps = (int)lerpf(64.f, 140.f, t);
        o.samples = 4;
    } else {
        float t = q / 0.3f;
        o.scale = lerpf(0.5f, 0.7f, t);
        o.cloud_scale = lerpf(0.4f, 0.45f, t);
        o.cloud_steps = (int)lerpf(40.f, 64.f, t);
        o.samples = q < 0.12f ? 1 : 2;
    }
    o.shadow_size = setting < 40 ? 1024 : 2048;
    return o;
}

/* --- one-off work at start-up --------------------------------------------- */
static unsigned make_noise3d(Renderer *r, int n, int mode) {
    unsigned t;
    glGenTextures(1, &t);
    glBindTexture(GL_TEXTURE_3D, t);
    glTexImage3D(GL_TEXTURE_3D, 0, GL_RGBA8, n, n, n, 0, GL_RGBA, GL_UNSIGNED_BYTE, NULL);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_S, GL_REPEAT);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_T, GL_REPEAT);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_R, GL_REPEAT);
    unsigned fbo;
    glGenFramebuffers(1, &fbo);
    glBindFramebuffer(GL_FRAMEBUFFER, fbo);
    glViewport(0, 0, n, n);
    glUseProgram(r->p_noise);
    u1i(r->p_noise, "uMode", mode);
    for (int z = 0; z < n; ++z) {
        glFramebufferTextureLayer(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, t, 0, z);
        u1f(r->p_noise, "uZ", ((float)z + 0.5f) / (float)n);
        draw_fullscreen();
        /* a slow GPU gets the work in small pieces: one long burst can
         * outlast Windows' two-second GPU watchdog and reset the driver */
        if ((z & 7) == 7) glFinish();
    }
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    glDeleteFramebuffers(1, &fbo);
    glBindTexture(GL_TEXTURE_3D, t);
    glGenerateMipmap(GL_TEXTURE_3D);
    return t;
}

static void build_terrain_grid(Renderer *r) {
    int n = TERRAIN_GRID + 1;
    float *v = malloc(sizeof(float) * 2 * (size_t)n * n);
    unsigned *idx = malloc(sizeof(unsigned) * 6 * (size_t)TERRAIN_GRID * TERRAIN_GRID);
    for (int z = 0; z < n; ++z)
        for (int x = 0; x < n; ++x) {
            v[(z * n + x) * 2] = (float)x;
            v[(z * n + x) * 2 + 1] = (float)z;
        }
    int k = 0;
    for (int z = 0; z < TERRAIN_GRID; ++z)
        for (int x = 0; x < TERRAIN_GRID; ++x) {
            unsigned a = (unsigned)(z * n + x), b = a + 1, c = a + (unsigned)n, d = c + 1;
            idx[k++] = a; idx[k++] = c; idx[k++] = b;
            idx[k++] = b; idx[k++] = c; idx[k++] = d;
        }
    glGenVertexArrays(1, &r->terr_vao);
    glGenBuffers(1, &r->terr_vbo);
    glGenBuffers(1, &r->terr_ibo);
    glBindVertexArray(r->terr_vao);
    glBindBuffer(GL_ARRAY_BUFFER, r->terr_vbo);
    glBufferData(GL_ARRAY_BUFFER, (GLsizeiptr)(sizeof(float) * 2 * (size_t)n * n), v, GL_STATIC_DRAW);
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 8, (void *)0);
    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, r->terr_ibo);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, (GLsizeiptr)(sizeof(unsigned) * (size_t)k), idx, GL_STATIC_DRAW);
    glBindVertexArray(r->vao);
    r->terr_indices = k;
    free(v);
    free(idx);
}

static void build_shadow(Renderer *r, int size) {
    del_tex(&r->t_shadow);
    del_fbo(&r->f_shadow);
    glGenTextures(1, &r->t_shadow);
    glBindTexture(GL_TEXTURE_2D, r->t_shadow);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_DEPTH_COMPONENT24, size, size, 0, GL_DEPTH_COMPONENT, GL_FLOAT, NULL);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glGenFramebuffers(1, &r->f_shadow);
    glBindFramebuffer(GL_FRAMEBUFFER, r->f_shadow);
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_TEXTURE_2D, r->t_shadow, 0);
    glDrawBuffer(GL_NONE);
    glReadBuffer(GL_NONE);
    if (glCheckFramebufferStatus(GL_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE)
        plat_log("shadow framebuffer incomplete");
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    r->shadow_size = size;
}

int render_init(Renderer *r, int quality) {
    memset(r, 0, sizeof *r);
    r->q = render_quality(quality > 0 ? quality : 60);
    plat_log("GL %s / %s / %s", (const char *)glGetString(GL_VENDOR), (const char *)glGetString(GL_RENDERER),
             (const char *)glGetString(GL_VERSION));
    plat_log("GLSL %s", (const char *)glGetString(0x8B8C /* GL_SHADING_LANGUAGE_VERSION */));
    {
        GLint v[8] = { 0 };
        glGetIntegerv(GL_MAX_TEXTURE_SIZE, &v[0]);
        glGetIntegerv(0x8073 /* GL_MAX_3D_TEXTURE_SIZE */, &v[1]);
        glGetIntegerv(0x8B49 /* GL_MAX_FRAGMENT_UNIFORM_COMPONENTS */, &v[2]);
        glGetIntegerv(0x8B4A /* GL_MAX_VERTEX_UNIFORM_COMPONENTS */, &v[3]);
        glGetIntegerv(0x8872 /* GL_MAX_TEXTURE_IMAGE_UNITS */, &v[4]);
        glGetIntegerv(0x8D57 /* GL_MAX_SAMPLES */, &v[5]);
        glGetIntegerv(0x910E /* GL_MAX_COLOR_TEXTURE_SAMPLES */, &v[6]);
        glGetIntegerv(0x8824 /* GL_MAX_DRAW_BUFFERS */, &v[7]);
        plat_log("limits: tex %d, 3D %d, frag uniforms %d, vert uniforms %d, units %d, samples %d / colour %d, draw buffers %d",
                 v[0], v[1], v[2], v[3], v[4], v[5], v[6], v[7]);
    }
    plat_log("start: compiling shaders");

    const char *C = shader_common_glsl, *A = shader_atmosphere_glsl, *T = shader_terrain_fn_glsl,
               *CL = shader_cloud_fn_glsl;

    r->p_trans   = post_program(A, NULL, NULL, shader_lut_transmittance_frag, "transmittance");
    r->p_multi   = post_program(A, NULL, NULL, shader_lut_multiscatter_frag, "multiscatter");
    r->p_skyview = post_program(A, NULL, NULL, shader_lut_skyview_frag, "skyview");
    r->p_aerial  = post_program(A, NULL, NULL, shader_lut_aerial_frag, "aerial");
    r->p_noise   = post_program(NULL, NULL, NULL, shader_noise3d_frag, "noise3d");
    r->p_weather = post_program(NULL, NULL, NULL, shader_weather_frag, "weather");
    r->p_cshadow = post_program(CL, NULL, NULL, shader_cloudshadow_frag, "cloudshadow");
    r->p_probe   = post_program(A, CL, NULL, shader_probe_frag, "probe");
    r->p_sky     = post_program(A, NULL, NULL, shader_sky_frag, "sky");
    r->p_clouds  = post_program(A, CL, NULL, shader_clouds_frag, "clouds");
    r->p_composite = post_program(NULL, NULL, NULL, shader_composite_frag, "composite");
    r->p_cloudtaa = post_program(NULL, NULL, NULL, shader_cloudtaa_frag, "cloudtaa");
    r->p_lum     = post_program(NULL, NULL, NULL, shader_lum_frag, "lum");
    r->p_adapt   = post_program(NULL, NULL, NULL, shader_adapt_frag, "adapt");
    r->p_bright  = post_program(NULL, NULL, NULL, shader_bright_frag, "bright");
    r->p_blur    = post_program(NULL, NULL, NULL, shader_blur_frag, "blur");
    r->p_blit    = post_program(NULL, NULL, NULL, shader_blit_frag, "blit");
    r->p_final   = post_program(NULL, NULL, NULL, shader_final_frag, "final");
    r->p_present = post_program(NULL, NULL, NULL, shader_present_frag, "present");
    r->p_resolve = post_program(NULL, NULL, NULL, shader_msresolve_frag, "msresolve");
    {
        const char *vs[] = { C, T, shader_terrain_vert };
        const char *fs[] = { C, A, T, shader_terrain_frag };
        r->p_terrain = render_program(vs, 3, fs, 4, "terrain");
    }
    {
        const char *vs[] = { C, shader_aircraft_vert };
        const char *fs[] = { C, A, shader_aircraft_frag };
        r->p_aircraft = render_program(vs, 2, fs, 3, "aircraft");
        const char *fs2[] = { shader_shadow_frag };
        r->p_shadow = render_program(vs, 2, fs2, 1, "shadow");
    }
    {
        const char *vs[] = { C, shader_precip_vert };
        const char *fs[] = { C, shader_precip_frag };
        r->p_precip = render_program(vs, 2, fs, 2, "precip");
        const char *vs2[] = { C, shader_bolt_vert };
        const char *fs2[] = { C, shader_bolt_frag };
        r->p_bolt = render_program(vs2, 2, fs2, 2, "bolt");
        const char *vs3[] = { C, shader_lights_vert };
        const char *fs3[] = { C, shader_lights_frag };
        r->p_lights = render_program(vs3, 2, fs3, 2, "lights");
        const char *vs4[] = { C, shader_trail_vert };
        const char *fs4[] = { C, shader_trail_frag };
        r->p_trail = render_program(vs4, 2, fs4, 2, "trail");
    }
    unsigned progs[] = { r->p_trans, r->p_multi, r->p_skyview, r->p_aerial, r->p_noise, r->p_weather,
                         r->p_cshadow, r->p_probe, r->p_sky, r->p_clouds, r->p_composite, r->p_lum,
                         r->p_adapt, r->p_bright, r->p_blur, r->p_blit, r->p_final, r->p_terrain,
                         r->p_aircraft, r->p_shadow, r->p_precip, r->p_bolt, r->p_lights, r->p_trail, r->p_cloudtaa,
                         r->p_present, r->p_resolve };
    for (size_t i = 0; i < sizeof progs / sizeof *progs; ++i)
        if (!progs[i]) return 0;

    glGenVertexArrays(1, &r->vao);
    glBindVertexArray(r->vao);

    /* atmosphere LUTs */
    r->t_trans = make_tex2d(TRANS_W, TRANS_H, GL_RGBA16F, GL_RGBA, GL_FLOAT, GL_LINEAR, GL_CLAMP_TO_EDGE);
    r->f_trans = make_fbo(r->t_trans, 0);
    r->t_multi = make_tex2d(MULTI_N, MULTI_N, GL_RGBA16F, GL_RGBA, GL_FLOAT, GL_LINEAR, GL_CLAMP_TO_EDGE);
    r->f_multi = make_fbo(r->t_multi, 0);
    r->t_skyview = make_tex2d(SKYVIEW_W, SKYVIEW_H, GL_RGBA16F, GL_RGBA, GL_FLOAT, GL_LINEAR_MIPMAP_LINEAR, GL_CLAMP_TO_EDGE);
    glBindTexture(GL_TEXTURE_2D, r->t_skyview);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
    glGenerateMipmap(GL_TEXTURE_2D);
    r->f_skyview = make_fbo(r->t_skyview, 0);
    r->t_aerial = make_tex2d(AP_N * AP_N, AP_N, GL_RGBA16F, GL_RGBA, GL_FLOAT, GL_LINEAR, GL_CLAMP_TO_EDGE);
    r->t_aerialT = make_tex2d(AP_N * AP_N, AP_N, GL_RGBA16F, GL_RGBA, GL_FLOAT, GL_LINEAR, GL_CLAMP_TO_EDGE);
    r->f_aerial = make_fbo(r->t_aerial, r->t_aerialT);
    r->atmo_key[0] = -1.f;

    /* clouds */
    plat_log("start: shaders done, building cloud noise");
    Uint64 t0 = SDL_GetTicks();
    r->t_noise_base = make_noise3d(r, NOISE_BASE, 0);
    r->t_noise_detail = make_noise3d(r, NOISE_DETAIL, 1);
    glFinish();
    plat_log("cloud noise built in %u ms", (unsigned)(SDL_GetTicks() - t0));
    r->t_weather = make_tex2d(WEATHER_N, WEATHER_N, GL_RGBA16F, GL_RGBA, GL_FLOAT, GL_LINEAR, GL_CLAMP_TO_EDGE);
    r->f_weather = make_fbo(r->t_weather, 0);
    r->t_cshadow = make_tex2d(CSHADOW_N, CSHADOW_N, GL_R16F, GL_RED, GL_FLOAT, GL_LINEAR, GL_CLAMP_TO_EDGE);
    r->f_cshadow = make_fbo(r->t_cshadow, 0);
    r->t_probe = make_tex2d(4, 1, GL_RGBA16F, GL_RGBA, GL_FLOAT, GL_NEAREST, GL_CLAMP_TO_EDGE);
    r->f_probe = make_fbo(r->t_probe, 0);

    /* the eye */
    r->t_lum = make_tex2d(LUM_N, LUM_N, GL_RG16F, GL_RG, GL_FLOAT, GL_LINEAR_MIPMAP_LINEAR, GL_CLAMP_TO_EDGE);
    glBindTexture(GL_TEXTURE_2D, r->t_lum);
    glGenerateMipmap(GL_TEXTURE_2D);
    r->f_lum = make_fbo(r->t_lum, 0);
    r->lum_levels = 0;
    for (int n = LUM_N; n > 1; n >>= 1) r->lum_levels++;
    for (int i = 0; i < 2; ++i) {
        r->t_adapt[i] = make_tex2d(1, 1, GL_R32F, GL_RED, GL_FLOAT, GL_NEAREST, GL_CLAMP_TO_EDGE);
        r->f_adapt[i] = make_fbo(r->t_adapt[i], 0);
    }
    r->adapt_reset = 1;

    /* the aircraft and the ground */
    if (!model_load(&r->model)) return 0;
    r->decal_count = model_livery(r->decals, MAX_DECALS);
    for (int i = 0; i < r->decal_count; ++i)
        plat_log("decal %2d: z %.2f y %.2f w %.2f h %.2f side %+.0f part %.0f xc %.2f reach %.1f uv %.3f %.3f %.3f %.3f", i,
                 r->decals[i].zc, r->decals[i].yc, r->decals[i].w, r->decals[i].h, r->decals[i].side, r->decals[i].part,
                 r->decals[i].xc, r->decals[i].reach, r->decals[i].u0, r->decals[i].v0, r->decals[i].u1, r->decals[i].v1);
    build_shadow(r, r->q.shadow_size);
    build_terrain_grid(r);
    glGenBuffers(1, &r->bolt_vbo);
    glGenBuffers(1, &r->trail_vbo);

    glGenQueries(3, r->gpu_query);
    r->query_ok = 1;
    while (glGetError() != GL_NO_ERROR) {}
    gl_check("render_init");
    return 1;
}

/* --- window-sized targets ------------------------------------------------- */
void render_resize(Renderer *r, int w, int h) {
    r->width = w > 1 ? w : 1;
    r->height = h > 1 ? h : 1;
    r->w = (int)(r->width * r->q.scale + 0.5f);
    r->h = (int)(r->height * r->q.scale + 0.5f);
    if (r->w < 1) r->w = 1;
    if (r->h < 1) r->h = 1;
    r->cw = (int)(r->w * r->q.cloud_scale + 0.5f);
    r->ch = (int)(r->h * r->q.cloud_scale + 0.5f);
    if (r->cw < 1) r->cw = 1;
    if (r->ch < 1) r->ch = 1;
    if (r->shadow_size != r->q.shadow_size) build_shadow(r, r->q.shadow_size);
}

static void ensure_targets(Renderer *r) {
    if (r->built_w == r->w && r->built_h == r->h && r->built_cw == r->cw && r->built_ch == r->ch && r->f_scene &&
        r->built_samples == r->q.samples)
        return;
    del_tex(&r->t_scene); del_tex(&r->t_dist); del_fbo(&r->f_scene);
    if (r->rb_depth) { glDeleteRenderbuffers(1, &r->rb_depth); r->rb_depth = 0; }
    del_tex(&r->t_comp); del_fbo(&r->f_comp);
    del_tex(&r->t_ms_color); del_tex(&r->t_ms_dist); del_fbo(&r->f_ms);
    if (r->rb_ms_depth) { glDeleteRenderbuffers(1, &r->rb_ms_depth); r->rb_ms_depth = 0; }
    del_tex(&r->t_clouds); del_tex(&r->t_cdepth); del_fbo(&r->f_clouds);
    for (int i = 0; i < 2; ++i) { del_tex(&r->t_hist[i]); del_tex(&r->t_hdepth[i]); del_fbo(&r->f_hist[i]); }
    for (int i = 0; i < 2; ++i) { del_tex(&r->t_bloom[i]); del_fbo(&r->f_bloom[i]); }

    r->t_scene = make_tex2d(r->w, r->h, GL_RGBA16F, GL_RGBA, GL_FLOAT, GL_LINEAR, GL_CLAMP_TO_EDGE);
    /* r: the nearest sample's distance; g: how much of the pixel lies well
     * beyond it (an edge's background share, from the multisample fold) */
    r->t_dist = make_tex2d(r->w, r->h, GL_RG32F, GL_RG, GL_FLOAT, GL_NEAREST, GL_CLAMP_TO_EDGE);
    glGenRenderbuffers(1, &r->rb_depth);
    glBindRenderbuffer(GL_RENDERBUFFER, r->rb_depth);
    glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT24, r->w, r->h);
    r->f_scene = make_fbo(r->t_scene, r->t_dist);
    glBindFramebuffer(GL_FRAMEBUFFER, r->f_scene);
    glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, r->rb_depth);
    if (glCheckFramebufferStatus(GL_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE) plat_log("scene target incomplete");

    /* The multisampled scene: four samples a pixel, two past ~1440p where the
     * pixels are small anyway and four would cost half a gigabyte. */
    r->samples = (long)r->w * r->h > 4200000L ? 2 : 4;
    if (r->q.samples < r->samples) r->samples = r->q.samples;
    {
        GLint mx = 0, mc = 0, md = 0;
        glGetIntegerv(0x910E /* GL_MAX_COLOR_TEXTURE_SAMPLES */, &mc);
        glGetIntegerv(0x910F /* GL_MAX_DEPTH_TEXTURE_SAMPLES */, &md);
        glGetIntegerv(0x8D57 /* GL_MAX_SAMPLES */, &mx);
        int lim = mc;
        if (mx > 0 && mx < lim) lim = mx;
        if (lim < 1) lim = 1;
        if (r->samples > lim) r->samples = lim;
        if (r->ms_broken) r->samples = 1;
    }
    msaa_again:
    glGenTextures(1, &r->t_ms_color);
    glBindTexture(GL_TEXTURE_2D_MULTISAMPLE, r->t_ms_color);
    glTexImage2DMultisample(GL_TEXTURE_2D_MULTISAMPLE, r->samples, GL_RGBA16F, r->w, r->h, GL_TRUE);
    glGenTextures(1, &r->t_ms_dist);
    glBindTexture(GL_TEXTURE_2D_MULTISAMPLE, r->t_ms_dist);
    glTexImage2DMultisample(GL_TEXTURE_2D_MULTISAMPLE, r->samples, GL_R32F, r->w, r->h, GL_TRUE);
    glBindTexture(GL_TEXTURE_2D_MULTISAMPLE, 0);
    glGenRenderbuffers(1, &r->rb_ms_depth);
    glBindRenderbuffer(GL_RENDERBUFFER, r->rb_ms_depth);
    glRenderbufferStorageMultisample(GL_RENDERBUFFER, r->samples, GL_DEPTH_COMPONENT24, r->w, r->h);
    glGenFramebuffers(1, &r->f_ms);
    glBindFramebuffer(GL_FRAMEBUFFER, r->f_ms);
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D_MULTISAMPLE, r->t_ms_color, 0);
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT1, GL_TEXTURE_2D_MULTISAMPLE, r->t_ms_dist, 0);
    glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, r->rb_ms_depth);
    {
        GLenum b[2] = { GL_COLOR_ATTACHMENT0, GL_COLOR_ATTACHMENT1 };
        glDrawBuffers(2, b);
    }
    {
        GLenum st = glCheckFramebufferStatus(GL_FRAMEBUFFER);
        if (st != GL_FRAMEBUFFER_COMPLETE) {
            plat_log("multisampled scene target incomplete (0x%x) at %d samples", (unsigned)st, r->samples);
            if (r->samples > 1) {
                /* fewer samples, down to one: the scene still renders */
                del_tex(&r->t_ms_color); del_tex(&r->t_ms_dist); del_fbo(&r->f_ms);
                glDeleteRenderbuffers(1, &r->rb_ms_depth); r->rb_ms_depth = 0;
                r->samples = r->samples > 2 ? 2 : 1;
                if (r->samples == 1) r->ms_broken = 1;
                goto msaa_again;
            }
        }
        plat_log("scene: %d samples", r->samples);
    }

    r->t_comp = make_tex2d(r->w, r->h, GL_RGBA16F, GL_RGBA, GL_FLOAT, GL_LINEAR, GL_CLAMP_TO_EDGE);
    r->f_comp = make_fbo(r->t_comp, 0);
    glBindFramebuffer(GL_FRAMEBUFFER, r->f_comp);
    glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, r->rb_depth);
    if (glCheckFramebufferStatus(GL_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE) plat_log("composite target incomplete");

    r->t_clouds = make_tex2d(r->cw, r->ch, GL_RGBA16F, GL_RGBA, GL_FLOAT, GL_LINEAR, GL_CLAMP_TO_EDGE);
    r->t_cdepth = make_tex2d(r->cw, r->ch, GL_R32F, GL_RED, GL_FLOAT, GL_NEAREST, GL_CLAMP_TO_EDGE);
    r->f_clouds = make_fbo(r->t_clouds, r->t_cdepth);
    for (int i = 0; i < 2; ++i) {
        r->t_hist[i] = make_tex2d(r->cw, r->ch, GL_RGBA16F, GL_RGBA, GL_FLOAT, GL_LINEAR, GL_CLAMP_TO_EDGE);
        r->t_hdepth[i] = make_tex2d(r->cw, r->ch, GL_R32F, GL_RED, GL_FLOAT, GL_NEAREST, GL_CLAMP_TO_EDGE);
        r->f_hist[i] = make_fbo(r->t_hist[i], r->t_hdepth[i]);
    }
    r->hist_valid = 0;

    r->bloom_w = r->w / 4 > 1 ? r->w / 4 : 1;
    r->bloom_h = r->h / 4 > 1 ? r->h / 4 : 1;
    for (int i = 0; i < 2; ++i) {
        r->t_bloom[i] = make_tex2d(r->bloom_w, r->bloom_h, GL_RGBA16F, GL_RGBA, GL_FLOAT, GL_LINEAR, GL_CLAMP_TO_EDGE);
        r->f_bloom[i] = make_fbo(r->t_bloom[i], 0);
    }
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    r->built_samples = r->q.samples;
    r->built_w = r->w; r->built_h = r->h; r->built_cw = r->cw; r->built_ch = r->ch;
    plat_log("targets: scene %dx%d, clouds %dx%d", r->w, r->h, r->cw, r->ch);
}

/* --- per-frame lighting --------------------------------------------------- */
typedef struct Light {
    vec3  sun_dir, moon_dir;
    vec3  sun_illum, moon_illum;      /* pre-exposed */
    vec3  key_dir, key_illum;         /* whichever lights the clouds */
    vec3  fill_dir, fill_illum;
    float pre;                        /* the pre-exposure */
    float night;                      /* 0 day .. 1 night */
    float stars;
    float cam_rkm;
} Light;

static Light compute_light(const Frame *f) {
    Light L;
    const Weather *w = f->wx;
    L.sun_dir = weather_sun_dir(w);
    L.moon_dir = weather_moon_dir(w);
    float phase = clampf(w->moon_phase, 0.f, 1.f);
    float moon_amt = SUN_ILLUM * MOON_FRACTION * powf(phase, 1.5f) * smoothstepf(-2.f, 4.f, w->moon_elev);
    /* The pre-exposure: roughly how much light the scene has, so a noon and a
     * moonlit frame both land near 1.0 in the float target. */
    float sun_e = SUN_ILLUM * powf(smoothstepf(-12.f, 25.f, w->sun_elev), 2.2f) + SUN_ILLUM * 0.0006f;
    float moon_e = moon_amt * fmaxf(sinf(DEG2RAD(w->moon_elev)), 0.1f);
    float e = sun_e + moon_e;
    L.pre = 1.2f / fmaxf(e, 2.5e-3f);
    L.sun_illum = v3_scale(v3(1.f, 0.985f, 0.96f), SUN_ILLUM * L.pre);
    L.moon_illum = v3_scale(v3(0.95f, 0.97f, 1.f), moon_amt * L.pre);
    if (w->sun_elev > -7.f) {
        L.key_dir = L.sun_dir; L.key_illum = L.sun_illum;
        L.fill_dir = L.moon_dir; L.fill_illum = L.moon_illum;
    } else {
        L.key_dir = L.moon_dir; L.key_illum = L.moon_illum;
        L.fill_dir = L.sun_dir; L.fill_illum = L.sun_illum;
    }
    L.night = 1.f - smoothstepf(-12.f, -2.f, w->sun_elev);
    L.stars = w->stars * L.night * L.night * 0.9f;
    L.cam_rkm = (float)((6360000.0 + f->cam_pos.y) * 0.001);
    return L;
}

static void set_atmo(unsigned p, const Weather *w) {
    float haze = w->haze;
    u3f(p, "uRayleighScat", 5.802e-3f, 13.558e-3f, 33.1e-3f);
    u1f(p, "uRayleighH", 8.f);
    float mie = 3.996e-3f * haze * (1.f + w->humidity * 0.3f);
    u1f(p, "uMieScat", mie);
    u1f(p, "uMieExt", mie * 1.11f);
    u1f(p, "uMieH", fmaxf(w->haze_height, 300.f) * 0.001f);
    u1f(p, "uMieG", 0.76f + 0.06f * w->humidity);
    float dust = w->dust * haze;
    u3f(p, "uMieAbsorb", 0.3e-3f * dust, 1.5e-3f * dust, 4.5e-3f * dust);
    u3f(p, "uOzoneAbs", 0.650e-3f, 1.881e-3f, 0.085e-3f);
}

static vec3 ground_albedo(const Weather *w) {
    float a;
    switch (w->biome) {
    case BIOME_OCEAN:     a = 0.06f; break;
    case BIOME_MOUNTAINS: a = 0.22f; break;
    case BIOME_DESERT:    a = 0.35f; break;
    case BIOME_ARCTIC:    a = 0.8f;  break;
    case BIOME_TROPICAL:  a = 0.1f;  break;
    case BIOME_FOREST:    a = 0.1f;  break;
    case BIOME_COAST:     a = 0.12f; break;
    case BIOME_HIMALAYA:  a = 0.3f;  break;
    default:              a = 0.16f; break;
    }
    a = lerpf(a, 0.8f, w->snow_cover);
    return v3(a, a, a * 0.95f);
}

static void set_clouds(unsigned p, const Frame *f) {
    const Weather *w = f->wx;
    const WeatherState *ws = f->ws;
    u3f(p, "uCamWorld", (float)f->cam_pos.x, (float)f->cam_pos.y, (float)f->cam_pos.z);
    u2f(p, "uAirOffset", (float)ws->wind_offset_x, (float)ws->wind_offset_z);
    /* the weather map's centre, in air-mass coordinates, snapped to its texels */
    float texel = WEATHER_SIZE / WEATHER_N;
    double ax = f->cam_pos.x - ws->wind_offset_x, az = f->cam_pos.z - ws->wind_offset_z;
    float cx = (float)(floor(ax / texel) * texel), cz = (float)(floor(az / texel) * texel);
    u2f(p, "uWMCenter", cx, cz);
    u1f(p, "uWMSize", WEATHER_SIZE);
    u4f(p, "uLow0", w->low.base, w->low.top, w->low.cover, w->low.type);
    u4f(p, "uLow1", w->low.density, w->low.scale_km, w->low.erosion, 0.f);
    u4f(p, "uMid0", w->mid.base, w->mid.top, w->mid.cover, w->mid.type);
    u4f(p, "uMid1", w->mid.density, w->mid.scale_km, w->mid.erosion, 0.f);
    u1f(p, "uRain", fmaxf(w->rain, w->snow));
    u1f(p, "uTime", f->time);
    float wd = DEG2RAD(w->wind_dir);
    u2f(p, "uShearDir", -sinf(wd), cosf(wd));
}

static void set_terrain_params(unsigned p, const TerrainParams *t) {
    u4f(p, "uT0", t->base, t->cont_amp, t->cont_scale_km, t->hill_amp);
    u4f(p, "uT1", t->hill_scale_km, t->mtn_amp, t->mtn_scale_km, t->mtn_mask_lo);
    u4f(p, "uT2", t->mtn_mask_hi, t->river, t->river_scale_km, t->dune_amp);
    u4f(p, "uT3", t->snow_line, t->tree_line, (float)t->biome, (float)t->seed);
    u4f(p, "uT4", t->field_km, t->forest, t->towns, t->snow_cover);
    const TerrainParams *u = t->to ? t->to : t;
    u4f(p, "uT5", (float)t->biome2, t->to ? t->biome_mix : 0.f, 0.f, 0.f);
    u4f(p, "uU0", u->base, u->cont_amp, u->cont_scale_km, u->hill_amp);
    u4f(p, "uU1", u->hill_scale_km, u->mtn_amp, u->mtn_scale_km, u->mtn_mask_lo);
    u4f(p, "uU2", u->mtn_mask_hi, u->river, u->river_scale_km, u->dune_amp);
    u4f(p, "uU3", u->snow_line, u->tree_line, (float)u->biome, (float)u->seed);
    u4f(p, "uU4", u->field_km, u->forest, u->towns, u->snow_cover);
}

static void set_luts(unsigned p, Renderer *r, int first_unit) {
    tex(p, "uTransLUT", first_unit, GL_TEXTURE_2D, r->t_trans);
    tex(p, "uMultiLUT", first_unit + 1, GL_TEXTURE_2D, r->t_multi);
    tex(p, "uAerialLUT", first_unit + 2, GL_TEXTURE_2D, r->t_aerial);
    tex(p, "uAerialTLUT", first_unit + 3, GL_TEXTURE_2D, r->t_aerialT);
}

static void set_cloud_tex(unsigned p, Renderer *r, int first_unit) {
    tex(p, "uNoiseBase", first_unit, GL_TEXTURE_3D, r->t_noise_base);
    tex(p, "uNoiseDetail", first_unit + 1, GL_TEXTURE_3D, r->t_noise_detail);
    tex(p, "uWeatherMap", first_unit + 2, GL_TEXTURE_2D, r->t_weather);
}

/* The aircraft's lights: positions on the airframe, colours, and how they
 * flash. Returned camera-relative. */
typedef struct NavLight { vec3 pos; vec3 col; float on; float size; } NavLight;

static int nav_lights(const Frame *f, NavLight *out, float pre) {
    static const vec3 at[7] = {
        /* on the skin itself, measured off the mesh: the wingtips run from
         * z 8.3 to 11.3 at y -0.2, the fuselage's tail cone ends at z 35.2, y 3.1
         * (the fins sweep further aft, but the light is on the cone) */
        { -44.28f, -0.15f,  8.9f },  /* left wingtip, at its leading edge: red */
        {  44.28f, -0.15f,  8.9f },  /* right wingtip: green */
        {   0.0f,  3.12f, 35.25f },  /* tail cone: white */
        {   0.0f,  4.24f, -4.0f },   /* beacon on top */
        {   0.0f, -4.55f, -2.0f },   /* beacon underneath */
        { -44.32f, -0.17f,  9.7f },  /* strobes on the wingtips, just aft */
        {  44.32f, -0.17f,  9.7f },
    };
    float t = f->time;
    float beacon = powf(fmaxf(0.f, sinf(t * 2.f * MR_PI * 0.75f)), 12.f);
    float sp = fmodf(t, 1.2f);
    float strobe = (sp < 0.05f || (sp > 0.14f && sp < 0.19f)) ? 1.f : 0.f;
    vec3 cols[7] = { v3(1.f, 0.06f, 0.03f), v3(0.05f, 1.f, 0.2f), v3(1.f, 1.f, 1.f),
                     v3(1.f, 0.05f, 0.02f), v3(1.f, 0.05f, 0.02f), v3(0.9f, 0.95f, 1.f),
                     v3(0.9f, 0.95f, 1.f) };
    float power[7] = { 1.f, 1.f, 0.8f, 3.f * beacon, 3.f * beacon, 12.f * strobe, 12.f * strobe };
    dvec3 rel = dv3_sub(f->ac_pos, f->cam_pos);
    for (int i = 0; i < 7; ++i) {
        vec3 wp = basis_apply(f->ac_basis, at[i]);
        if (i == 0 || i == 1 || i == 5 || i == 6) {
            /* the wingtips ride the flex */
            wp = v3_add(wp, v3_scale(f->ac_basis.y, f->flex));
        }
        out[i].pos = v3_add(dv3_to_v3(rel), wp);
        out[i].col = v3_scale(cols[i], 0.004f * pre);
        out[i].on = power[i] * (f->nav_lights ? 1.f : 0.f);
        out[i].size = i >= 5 ? 0.35f : 0.22f;
    }
    return 7;
}

/* --- lightning channel ------------------------------------------------------ */
static int build_bolt(const Frame *f, float *out) {
    const WeatherState *ws = f->ws;
    if (!ws->bolt_visible || ws->flash < 0.02f) return 0;
    rng_t rng = { ws->bolt_seed | 1u };
    dvec3 top = ws->flash_pos;
    int n = 0;
    /* the main channel, jagged, down to the ground */
    vec3 p = dv3_to_v3(dv3_sub(top, f->cam_pos));
    float ground = (float)(0.0 - f->cam_pos.y);
    vec3 dir = v3(0.f, -1.f, 0.f);
    float seg = 180.f;
    while (p.y > ground && n < BOLT_MAX - 20) {
        dir = v3_norm(v3_add(v3(0.f, -1.f, 0.f), v3(rng_range(&rng, -0.9f, 0.9f), rng_range(&rng, -0.2f, 0.3f),
                                                       rng_range(&rng, -0.9f, 0.9f))));
        vec3 q = v3_add(p, v3_scale(dir, seg * rng_range(&rng, 0.5f, 1.3f)));
        float *o = out + n * 8;
        o[0] = p.x; o[1] = p.y; o[2] = p.z; o[3] = 6.f;
        o[4] = q.x; o[5] = q.y; o[6] = q.z; o[7] = 1.f;
        n++;
        /* branches */
        if (rng_f(&rng) < 0.12f && n < BOLT_MAX - 12) {
            vec3 b = q;
            vec3 bd = v3_norm(v3(rng_range(&rng, -1.f, 1.f), -0.6f, rng_range(&rng, -1.f, 1.f)));
            int len = 3 + rng_int(&rng, 6);
            for (int k = 0; k < len && n < BOLT_MAX; ++k) {
                vec3 c = v3_add(b, v3_scale(v3_norm(v3_add(bd, v3(rng_range(&rng, -0.5f, 0.5f), 0.f, rng_range(&rng, -0.5f, 0.5f)))),
                                            seg * 0.7f));
                float *ob = out + n * 8;
                ob[0] = b.x; ob[1] = b.y; ob[2] = b.z; ob[3] = 3.f;
                ob[4] = c.x; ob[5] = c.y; ob[6] = c.z; ob[7] = 0.45f;
                n++;
                b = c;
            }
        }
        p = q;
    }
    return n;
}

/* --- GPU timing -------------------------------------------------------------- */
static void gpu_timer_begin(Renderer *r) {
    if (!r->query_ok) return;
    int slot = r->query_slot, read = (slot + 1) % 3;
    if (r->query_live[read]) {
        GLuint ready = 0;
        glGetQueryObjectuiv(r->gpu_query[read], GL_QUERY_RESULT_AVAILABLE, &ready);
        if (ready) {
            GLuint64 ns = 0;
            glGetQueryObjectui64v(r->gpu_query[read], GL_QUERY_RESULT, &ns);
            r->query_live[read] = 0;
            if (ns > 0) r->last_frame_ms = (float)ns / 1e6f;
        }
    }
    glBeginQuery(GL_TIME_ELAPSED, r->gpu_query[slot]);
    if (glGetError() != GL_NO_ERROR) { r->query_ok = 0; return; }
    r->query_live[slot] = 1;
}
static void gpu_timer_end(Renderer *r) {
    if (!r->query_ok) return;
    glEndQuery(GL_TIME_ELAPSED);
    r->query_slot = (r->query_slot + 1) % 3;
}

int render_project_dir(const Frame *f, float aspect, vec3 dir, float *u, float *v) {
    float x = v3_dot(dir, f->cam_basis.x), y = v3_dot(dir, f->cam_basis.y), z = -v3_dot(dir, f->cam_basis.z);
    if (z <= 0.01f) return 0;
    float th = tanf(f->fov * 0.5f);
    *u = 0.5f + 0.5f * (x / z) / (th * aspect);
    *v = 0.5f + 0.5f * (y / z) / th;
    return 1;
}

/* ============================================================================
 * The frame.
 * ========================================================================== */
void render_frame(Renderer *r, const Frame *f) {
    gpu_timer_begin(r);
    ensure_targets(r);
    r->frame_index++;
    const Weather *w = f->wx;
    Light L = compute_light(f);
    float aspect = (float)r->width / (float)r->height;
    float th = tanf(f->fov * 0.5f);
    glBindVertexArray(r->vao);
    glDisable(GL_DEPTH_TEST);
    glDisable(GL_CULL_FACE);
    glDisable(GL_BLEND);

    /* --- 1. atmosphere ------------------------------------------------------ */
    float key[8] = { w->haze, w->haze_height, w->dust, w->humidity, (float)w->biome, w->snow_cover, 0, 0 };
    if (memcmp(key, r->atmo_key, sizeof key) &&
        (r->atmo_key[0] < 0.f || fabsf(f->time - r->atmo_t) > 0.5f)) {
        memcpy(r->atmo_key, key, sizeof key);
        r->atmo_t = f->time;
        glBindFramebuffer(GL_FRAMEBUFFER, r->f_trans);
        glViewport(0, 0, TRANS_W, TRANS_H);
        glUseProgram(r->p_trans);
        set_atmo(r->p_trans, w);
        draw_fullscreen();
        glBindFramebuffer(GL_FRAMEBUFFER, r->f_multi);
        glViewport(0, 0, MULTI_N, MULTI_N);
        glUseProgram(r->p_multi);
        set_atmo(r->p_multi, w);
        set_luts(r->p_multi, r, 0);
        u3v(r->p_multi, "uGroundAlbedo", ground_albedo(w));
        draw_fullscreen();
    }
    glBindFramebuffer(GL_FRAMEBUFFER, r->f_skyview);
    glViewport(0, 0, SKYVIEW_W, SKYVIEW_H);
    glUseProgram(r->p_skyview);
    set_atmo(r->p_skyview, w);
    set_luts(r->p_skyview, r, 0);
    u1f(r->p_skyview, "uCamR", L.cam_rkm);
    u3v(r->p_skyview, "uSunDir", L.sun_dir);
    u3v(r->p_skyview, "uSunIllum", L.sun_illum);
    u3v(r->p_skyview, "uMoonDir", L.moon_dir);
    u3v(r->p_skyview, "uMoonIllum", L.moon_illum);
    draw_fullscreen();
    glBindTexture(GL_TEXTURE_2D, r->t_skyview);
    glGenerateMipmap(GL_TEXTURE_2D);

    glBindFramebuffer(GL_FRAMEBUFFER, r->f_aerial);
    glViewport(0, 0, AP_N * AP_N, AP_N);
    glUseProgram(r->p_aerial);
    set_atmo(r->p_aerial, w);
    set_luts(r->p_aerial, r, 0);
    u1f(r->p_aerial, "uCamR", L.cam_rkm);
    u3v(r->p_aerial, "uSunDir", L.sun_dir);
    u3v(r->p_aerial, "uSunIllum", L.sun_illum);
    u3v(r->p_aerial, "uMoonDir", L.moon_dir);
    u3v(r->p_aerial, "uMoonIllum", L.moon_illum);
    um3(r->p_aerial, "uCamBasis", f->cam_basis);
    u2f(r->p_aerial, "uTanHalf", th * aspect, th);
    draw_fullscreen();

    /* --- 2. weather map and cloud shadows ------------------------------------ */
    glBindFramebuffer(GL_FRAMEBUFFER, r->f_weather);
    glViewport(0, 0, WEATHER_N, WEATHER_N);
    glUseProgram(r->p_weather);
    set_clouds(r->p_weather, f);
    u1f(r->p_weather, "uSeedW", (float)(f->tp->seed % 1000u) * 0.37f);
    draw_fullscreen();

    float hmin = w->low.cover > 0.f ? w->low.base : 1e5f, hmax = w->low.cover > 0.f ? w->low.top : 0.f;
    if (w->mid.cover > 0.f) { hmin = fminf(hmin, w->mid.base); hmax = fmaxf(hmax, w->mid.top); }
    if (w->rain > 0.f || w->snow > 0.f) hmin = 0.f;
    if (hmax <= hmin) { hmin = 0.f; hmax = 1.f; }

    float cs_texel = CSHADOW_SIZE / CSHADOW_N;
    float csx = (float)(floor(f->cam_pos.x / cs_texel) * cs_texel);
    float csz = (float)(floor(f->cam_pos.z / cs_texel) * cs_texel);
    glBindFramebuffer(GL_FRAMEBUFFER, r->f_cshadow);
    glViewport(0, 0, CSHADOW_N, CSHADOW_N);
    glUseProgram(r->p_cshadow);
    set_clouds(r->p_cshadow, f);
    set_cloud_tex(r->p_cshadow, r, 0);
    u2f(r->p_cshadow, "uCSCenter", csx, csz);
    u1f(r->p_cshadow, "uCSSize", CSHADOW_SIZE);
    u3v(r->p_cshadow, "uLightDir", L.key_dir);
    u1f(r->p_cshadow, "uHMin", fmaxf(hmin, 0.f));
    u1f(r->p_cshadow, "uHMax", hmax);
    draw_fullscreen();

    /* --- 3. the probe --------------------------------------------------------- */
    vec3 ac_rel = dv3_to_v3(dv3_sub(f->ac_pos, f->cam_pos));
    glBindFramebuffer(GL_FRAMEBUFFER, r->f_probe);
    glViewport(0, 0, 4, 1);
    glUseProgram(r->p_probe);
    set_atmo(r->p_probe, w);
    set_luts(r->p_probe, r, 0);
    set_clouds(r->p_probe, f);
    set_cloud_tex(r->p_probe, r, 4);
    tex(r->p_probe, "uSkyView", 7, GL_TEXTURE_2D, r->t_skyview);
    tex(r->p_probe, "uCloudShadow", 8, GL_TEXTURE_2D, r->t_cshadow);
    u3v(r->p_probe, "uAcRel", ac_rel);
    u3v(r->p_probe, "uLightDir", L.key_dir);
    u3v(r->p_probe, "uLightIllum", L.key_illum);
    u1f(r->p_probe, "uCamRkm", L.cam_rkm);
    u3v(r->p_probe, "uGroundAlbedo", ground_albedo(w));
    {
        /* how much of the view straight down is cloud tops */
        float below = 0.f;
        if (f->cam_pos.y > w->low.top) below = w->low.cover;
        if (f->cam_pos.y > w->mid.top) below = fmaxf(below, w->mid.cover);
        u1f(r->p_probe, "uBelowCloud", below);
    }
    draw_fullscreen();

    /* --- 4. the aircraft's shadow map ----------------------------------------- */
    mat4 shadow_vp = m4_identity();
    float shadow_on = L.key_dir.y > -0.02f ? 1.f : 0.f;
    {
        vec3 ld = L.key_dir;
        vec3 up = fabsf(ld.y) > 0.95f ? v3(1.f, 0.f, 0.f) : v3(0.f, 1.f, 0.f);
        vec3 zx = v3_norm(v3_cross(up, ld));
        vec3 zy = v3_cross(ld, zx);
        basis3 lb = { zx, zy, ld };
        mat4 view = m4_view(lb, ac_rel);
        mat4 proj = m4_ortho(-48.f, 48.f, -48.f, 48.f, -250.f, 250.f);
        shadow_vp = m4_mul(proj, view);
        glBindFramebuffer(GL_FRAMEBUFFER, r->f_shadow);
        glViewport(0, 0, r->shadow_size, r->shadow_size);
        glEnable(GL_DEPTH_TEST);
        glDepthFunc(GL_LESS);
        glClear(GL_DEPTH_BUFFER_BIT);
        if (shadow_on > 0.f) {
            glUseProgram(r->p_shadow);
            mat4 model = m4_model(f->ac_basis, ac_rel);
            um4(r->p_shadow, "uModel", &model);
            um4(r->p_shadow, "uViewProj", &shadow_vp);
            u3f(r->p_shadow, "uCenter", r->model.center[0], r->model.center[1], r->model.center[2]);
            u3f(r->p_shadow, "uHalf", r->model.half[0], r->model.half[1], r->model.half[2]);
            u1f(r->p_shadow, "uFlex", f->flex);
            u1f(r->p_shadow, "uFanAngle", f->fan_angle);
            u3v(r->p_shadow, "uSurf", f->surf);
            glEnable(GL_POLYGON_OFFSET_FILL);
            glPolygonOffset(1.5f, 2.f);
            model_draw(&r->model);
            glDisable(GL_POLYGON_OFFSET_FILL);
            glBindVertexArray(r->vao);
        }
    }

    /* --- 5. the opaque scene ---------------------------------------------------- */
    NavLight nl[7];
    nav_lights(f, nl, L.pre);
    /* the four brightest go to the clouds and the skin as point lights */
    float pp[16] = { 0 }, pc[12] = { 0 };
    {
        int order[7] = { 0, 1, 2, 3, 4, 5, 6 };
        for (int i = 0; i < 7; ++i)
            for (int j = i + 1; j < 7; ++j)
                if (nl[order[j]].on > nl[order[i]].on) { int t = order[i]; order[i] = order[j]; order[j] = t; }
        for (int k = 0; k < 4; ++k) {
            NavLight *n = &nl[order[k]];
            pp[k * 4] = n->pos.x; pp[k * 4 + 1] = n->pos.y; pp[k * 4 + 2] = n->pos.z;
            pp[k * 4 + 3] = n->on > 0.01f ? 1.f : 0.f;
            vec3 c = v3_scale(n->col, n->on * 140.f);   /* a glow on the skin, not a floodlight */
            pc[k * 3] = c.x; pc[k * 3 + 1] = c.y; pc[k * 3 + 2] = c.z;
        }
    }
    float flash_scene = f->ws->flash * L.pre * 0.012f;
    vec3 flash_rel = dv3_to_v3(dv3_sub(f->ws->flash_pos, f->cam_pos));

    glBindFramebuffer(GL_FRAMEBUFFER, r->f_ms);
    glViewport(0, 0, r->w, r->h);
    {
        float clear_c[4] = { 0.f, 0.f, 0.f, 1.f }, clear_d[4] = { 1e7f, 0.f, 0.f, 1.f };
        glClearBufferfv(GL_COLOR, 0, clear_c);
        glClearBufferfv(GL_COLOR, 1, clear_d);
    }
    glClear(GL_DEPTH_BUFFER_BIT);
    mat4 view = m4_view(f->cam_basis, v3(0.f, 0.f, 0.f));
    float terr_near = clampf(f->agl * 0.35f, 5.f, 3000.f);
    mat4 proj_terr = m4_perspective_inf(f->fov, aspect, terr_near);
    mat4 vp_terr = m4_mul(proj_terr, view);
    float pixel_angle = 2.f * th / (float)r->h;

    /* terrain */
    glEnable(GL_DEPTH_TEST);
    glDepthFunc(GL_LESS);
    {
        TerrainGrid g;
        terrain_grid_layout(&g, f->cam_pos.x, f->cam_pos.z, fmaxf(f->agl, 50.f), TERRAIN_REACH);
        unsigned p = r->p_terrain;
        glUseProgram(p);
        set_atmo(p, w);
        set_luts(p, r, 0);
        set_terrain_params(p, f->tp);
        tex(p, "uProbe", 4, GL_TEXTURE_2D, r->t_probe);
        tex(p, "uSkyView", 5, GL_TEXTURE_2D, r->t_skyview);
        tex(p, "uCloudShadow", 6, GL_TEXTURE_2D, r->t_cshadow);
        tex(p, "uAcShadow", 7, GL_TEXTURE_2D, r->t_shadow);
        glUniform3f(loc(p, "uCamWorld"), (float)f->cam_pos.x, (float)f->cam_pos.y, (float)f->cam_pos.z);
        um4(p, "uViewProj", &vp_terr);
        u1f(p, "uGridN", (float)TERRAIN_GRID);
        u1f(p, "uPixelAngle", pixel_angle);
        u2f(p, "uRes", (float)r->w, (float)r->h);
        u3v(p, "uLightDir", L.key_dir);
        u3v(p, "uLightIllum", L.key_illum);
        u3v(p, "uMoonDir2", L.fill_dir);
        u3v(p, "uMoonIllum2", L.fill_illum);
        u2f(p, "uCSCenter", csx, csz);
        u1f(p, "uCSSize", CSHADOW_SIZE);
        /* past the shadow map, the cloud cover's average shadow */
        {
            float cov = fmaxf(w->low.cover * fminf(w->low.density, 1.5f), w->mid.cover * 0.6f);
            u1f(p, "uCSMean", 1.f - 0.55f * clampf(cov, 0.f, 1.f));
        }
        u1f(p, "uNight", L.night);
        u1f(p, "uCityLights", w->city_lights * L.pre * 0.4f);
        u1f(p, "uWetness", w->wetness);
        u1f(p, "uSeaState", w->sea_state);
        u1f(p, "uTime", f->time);
        u1f(p, "uFlash", flash_scene);
        u3v(p, "uFlashRel", flash_rel);
        um4(p, "uAcShadowMat", &shadow_vp);
        /* only the shadow of an aircraft in the sun, and only while it is
         * close enough to the ground to throw one worth seeing */
        u1f(p, "uAcShadowOn", shadow_on * (1.f - smoothstepf(2500.f, 6000.f, f->agl)));
        glBindVertexArray(r->terr_vao);
        for (int i = 0; i < g.levels; ++i) {
            TerrainLevel *lv = &g.level[i];
            u2f(p, "uOriginRel", (float)(lv->origin_x - f->cam_pos.x), (float)(lv->origin_z - f->cam_pos.z));
            u2f(p, "uOriginWorld", (float)lv->origin_x, (float)lv->origin_z);
            u1f(p, "uSpacing", lv->spacing);
            if (i == 0) {
                u4f(p, "uHole", 1e9f, 1e9f, -1e9f, -1e9f);
            } else {
                TerrainLevel *in = &g.level[i - 1];
                float x0 = (float)(in->origin_x - f->cam_pos.x) + lv->spacing;
                float z0 = (float)(in->origin_z - f->cam_pos.z) + lv->spacing;
                float ext = TERRAIN_GRID * in->spacing - 2.f * lv->spacing;
                u4f(p, "uHole", x0, z0, x0 + ext, z0 + ext);
            }
            glDrawElements(GL_TRIANGLES, r->terr_indices, GL_UNSIGNED_INT, 0);
        }
        glBindVertexArray(r->vao);
    }

    /* sky, where nothing was drawn */
    glDepthFunc(GL_LEQUAL);
    glDepthMask(GL_FALSE);
    {
        unsigned p = r->p_sky;
        glUseProgram(p);
        set_atmo(p, w);
        set_luts(p, r, 0);
        tex(p, "uSkyView", 4, GL_TEXTURE_2D, r->t_skyview);
        um3(p, "uCamBasis", f->cam_basis);
        u2f(p, "uTanHalf", th * aspect, th);
        u1f(p, "uCamRkm", L.cam_rkm);
        u3v(p, "uSunDir", L.sun_dir);
        u3v(p, "uSunIllum", L.sun_illum);
        u3v(p, "uMoonDir", L.moon_dir);
        u3v(p, "uMoonIllum", L.moon_illum);
        u1f(p, "uMoonPhase", w->moon_phase);
        u1f(p, "uStars", L.stars);
        u1f(p, "uAurora", w->aurora * L.night);
        u1f(p, "uTime", f->time);
        u1f(p, "uPixelAngle", pixel_angle);
        /* drawn at the far plane: gl_Position.z = 1 is what post.vert gives
         * with depth 0.5 in window space - so test with the depth forced */
        glDepthRange(1.0, 1.0);
        draw_fullscreen();
        glDepthRange(0.0, 1.0);
    }
    glDepthMask(GL_TRUE);
    glDepthFunc(GL_LESS);

    /* the aircraft, in its own depth range */
    glClear(GL_DEPTH_BUFFER_BIT);
    mat4 proj_ac = m4_perspective_inf(f->fov, aspect, f->near_plane);
    mat4 vp_ac = m4_mul(proj_ac, view);
    r->view_proj = vp_ac;
    {
        unsigned p = r->p_aircraft;
        glUseProgram(p);
        set_atmo(p, w);
        set_luts(p, r, 0);
        tex(p, "uProbe", 4, GL_TEXTURE_2D, r->t_probe);
        tex(p, "uSkyView", 5, GL_TEXTURE_2D, r->t_skyview);
        tex(p, "uShadowMap", 6, GL_TEXTURE_2D, r->t_shadow);
        tex(p, "uDecals", 7, GL_TEXTURE_2D, r->model.decal_tex);
        tex(p, "uBands", 8, GL_TEXTURE_2D, r->model.skin_tex);
        mat4 model = m4_model(f->ac_basis, ac_rel);
        um4(p, "uModel", &model);
        um4(p, "uViewProj", &vp_ac);
        u3f(p, "uCenter", r->model.center[0], r->model.center[1], r->model.center[2]);
        u3f(p, "uHalf", r->model.half[0], r->model.half[1], r->model.half[2]);
        u1f(p, "uFlex", f->flex);
        u1f(p, "uFanAngle", f->fan_angle);
        u1f(p, "uFanBlur", f->fan_blur);
        /* glow: exposure-compressed, faint by day, not blinding at night */
        u1f(p, "uEmit", powf(L.pre, 0.35f));
        u3v(p, "uSurf", f->surf);
        u1f(p, "uFanAngle", f->fan_angle);
        u2f(p, "uDecalSize", (float)r->model.decal_w, (float)r->model.decal_h);
        {
            float a[MAX_DECALS * 4], b[MAX_DECALS * 4], c[MAX_DECALS * 4], d[MAX_DECALS * 4];
            for (int i = 0; i < r->decal_count; ++i) {
                const Decal *dc = &r->decals[i];
                a[i * 4] = dc->zc; a[i * 4 + 1] = dc->yc; a[i * 4 + 2] = dc->w; a[i * 4 + 3] = dc->h;
                b[i * 4] = dc->u0; b[i * 4 + 1] = dc->v0; b[i * 4 + 2] = dc->u1; b[i * 4 + 3] = dc->v1;
                c[i * 4] = dc->side; c[i * 4 + 1] = dc->part; c[i * 4 + 2] = dc->xc; c[i * 4 + 3] = dc->reach;
                d[i * 4] = cosf(dc->angle); d[i * 4 + 1] = sinf(dc->angle); d[i * 4 + 2] = dc->axis; d[i * 4 + 3] = 0.f;
            }
            glUniform4fv(loc(p, "uDecA"), r->decal_count, a);
            glUniform4fv(loc(p, "uDecB"), r->decal_count, b);
            glUniform4fv(loc(p, "uDecC"), r->decal_count, c);
            glUniform4fv(loc(p, "uDecD"), r->decal_count, d);
            u1i(p, "uDecCount", r->decal_count);
        }
        u3v(p, "uLightDir", L.key_dir);
        u1f(p, "uCamRkm", L.cam_rkm);
        um4(p, "uShadowMat", &shadow_vp);
        u1f(p, "uShadowOn", shadow_on);
        u2f(p, "uRes", (float)r->w, (float)r->h);
        u1f(p, "uWet", fmaxf(w->rain, w->wetness * 0.5f));
        u1f(p, "uFlash", flash_scene);
        u3v(p, "uFlashRel", flash_rel);
        glUniform4fv(loc(p, "uPointPos"), 4, pp);
        glUniform3fv(loc(p, "uPointCol"), 4, pc);
        model_draw(&r->model);
        glBindVertexArray(r->vao);
    }
    glDisable(GL_DEPTH_TEST);

    /* --- 5b. fold the samples: colour averaged, distance the nearest, depth
     * from one sample for what is drawn on top later ------------------------------ */
    glDisable(GL_DEPTH_TEST);
    glBindFramebuffer(GL_FRAMEBUFFER, r->f_scene);
    glViewport(0, 0, r->w, r->h);
    glUseProgram(r->p_resolve);
    tex(r->p_resolve, "uColorMS", 0, GL_TEXTURE_2D_MULTISAMPLE, r->t_ms_color);
    tex(r->p_resolve, "uDistMS", 1, GL_TEXTURE_2D_MULTISAMPLE, r->t_ms_dist);
    glUniform1i(loc(r->p_resolve, "uSamples"), r->samples);
    draw_fullscreen();
    glBindFramebuffer(GL_READ_FRAMEBUFFER, r->f_ms);
    glBindFramebuffer(GL_DRAW_FRAMEBUFFER, r->f_scene);
    glBlitFramebuffer(0, 0, r->w, r->h, 0, 0, r->w, r->h, GL_DEPTH_BUFFER_BIT, GL_NEAREST);
    glBindFramebuffer(GL_FRAMEBUFFER, 0);

    /* --- 6. the clouds ------------------------------------------------------------ */
    glBindFramebuffer(GL_FRAMEBUFFER, r->f_clouds);
    glViewport(0, 0, r->cw, r->ch);
    {
        unsigned p = r->p_clouds;
        glUseProgram(p);
        set_atmo(p, w);
        set_luts(p, r, 0);
        set_clouds(p, f);
        set_cloud_tex(p, r, 4);
        tex(p, "uDistTex", 7, GL_TEXTURE_2D, r->t_dist);
        tex(p, "uProbe", 8, GL_TEXTURE_2D, r->t_probe);
        /* the aircraft: 45 m round its middle, however far the camera is */
        u1f(p, "uAircraftReach", v3_len(ac_rel) + 48.f);
        um3(p, "uCamBasis", f->cam_basis);
        u2f(p, "uTanHalf", th * aspect, th);
        u2f(p, "uFullRes", (float)r->w, (float)r->h);
        u1f(p, "uFrame", (float)(r->frame_index % 64u));
        glUniform1i(loc(p, "uSteps"), r->q.cloud_steps);
        u1f(p, "uMaxDist", clampf(60000.f + (float)f->cam_pos.y * 8.f, 60000.f, 160000.f));
        u1f(p, "uHMin", hmin);
        u1f(p, "uHMax", hmax);
        u3v(p, "uLightDir", L.key_dir);
        u3v(p, "uLightIllum", L.key_illum);
        u2f(p, "uCirrus", w->cirrus_cover, w->cirrus_alt);
        float wd = DEG2RAD(w->wind_dir);
        u2f(p, "uCirrusDir", -sinf(wd), cosf(wd));
        u1f(p, "uFlash", flash_scene);
        u3v(p, "uFlashRel", flash_rel);
        glUniform4fv(loc(p, "uPointPos"), 4, pp);
        glUniform3fv(loc(p, "uPointCol"), 4, pc);
        vec3 glow = v3_scale(v3(1.f, 0.62f, 0.3f), w->city_lights * L.night * L.pre * 0.00006f);
        u3v(p, "uCityGlow", glow);
        draw_fullscreen();
    }

    /* --- 6b. accumulate them over frames -------------------------------------------- */
    {
        int out = r->hist_idx ^ 1;
        dvec3 dcam = dv3_sub(f->cam_pos, r->prev_cam);
        /* a cut, a jump or a new window: nothing in the history is usable */
        int valid = r->hist_valid && dv3_dot(dcam, dcam) < 400.0 * 400.0 && f->fade < 0.5 &&
                    v3_dot(r->prev_basis.z, f->cam_basis.z) > 0.7;
        glBindFramebuffer(GL_FRAMEBUFFER, r->f_hist[out]);
        glViewport(0, 0, r->cw, r->ch);
        unsigned p = r->p_cloudtaa;
        glUseProgram(p);
        tex(p, "uCur", 0, GL_TEXTURE_2D, r->t_clouds);
        tex(p, "uCurDepth", 1, GL_TEXTURE_2D, r->t_cdepth);
        tex(p, "uHist", 2, GL_TEXTURE_2D, r->t_hist[r->hist_idx]);
        tex(p, "uHistDepth", 3, GL_TEXTURE_2D, r->t_hdepth[r->hist_idx]);
        um3(p, "uCamBasis", f->cam_basis);
        u2f(p, "uTanHalf", th * aspect, th);
        um3(p, "uPrevBasis", r->prev_basis);
        u2f(p, "uPrevTanHalf", r->prev_th * r->prev_aspect, r->prev_th);
        u3f(p, "uCamDelta", (float)dcam.x, (float)dcam.y, (float)dcam.z);
        u1f(p, "uBlend", valid ? 0.88f : 0.f);
        u2f(p, "uRes", (float)r->cw, (float)r->ch);
        draw_fullscreen();
        r->hist_idx = out;
        r->hist_valid = 1;
        r->prev_cam = f->cam_pos;
        r->prev_basis = f->cam_basis;
        r->prev_th = th;
        r->prev_aspect = aspect;
    }

    /* --- 7. composite and what goes on top ------------------------------------------ */
    glBindFramebuffer(GL_FRAMEBUFFER, r->f_comp);
    glViewport(0, 0, r->w, r->h);
    {
        unsigned p = r->p_composite;
        glUseProgram(p);
        tex(p, "uScene", 0, GL_TEXTURE_2D, r->t_scene);
        tex(p, "uDistTex", 1, GL_TEXTURE_2D, r->t_dist);
        tex(p, "uClouds", 2, GL_TEXTURE_2D, r->t_hist[r->hist_idx]);
        tex(p, "uCloudDepth", 5, GL_TEXTURE_2D, r->t_hdepth[r->hist_idx]);
        tex(p, "uProbe", 3, GL_TEXTURE_2D, r->t_probe);
        u2f(p, "uCloudRes", (float)r->cw, (float)r->ch);
        u2f(p, "uFullRes", (float)r->w, (float)r->h);
        u1f(p, "uPassage", f->passage);
        u1f(p, "uTime", f->time);
        um3(p, "uCamBasis", f->cam_basis);
        u2f(p, "uTanHalf", th * aspect, th);
        {
            float pl[18];
            for (int e = 0; e < TRAIL_ENGINES; ++e) {
                vec3 wp = v3_add(ac_rel, basis_apply(f->ac_basis, trail_nozzle[e]));
                pl[e * 3] = wp.x; pl[e * 3 + 1] = wp.y; pl[e * 3 + 2] = wp.z;
            }
            glUniform3fv(loc(p, "uPlume"), 6, pl);
            u3v(p, "uPlumeDir", f->ac_basis.z);
            u1f(p, "uHaze", f->haze);
        }
        u1f(p, "uFlashScreen", f->ws->flash * 0.02f * (1.f - smoothstepf(3000.f, 12000.f, v3_len(flash_rel))) * L.night);
        draw_fullscreen();
    }
    glEnable(GL_DEPTH_TEST);
    glDepthMask(GL_FALSE);
    glEnable(GL_BLEND);
    /* rain and snow */
    if (w->rain > 0.f || w->snow > 0.f) {
        unsigned p = r->p_precip;
        glBlendFunc(GL_ONE, GL_ONE_MINUS_SRC_ALPHA);
        glUseProgram(p);
        um4(p, "uViewProj", &vp_ac);
        float box = 60.f;
        float snow = w->snow > w->rain ? 1.f : 0.f;
        float fall = snow > 0.5f ? 1.5f : 9.f;
        float wdr = DEG2RAD(w->wind_dir);
        dvec3 drop_v = dv3(-sin(wdr) * w->wind_speed, -fall, cos(wdr) * w->wind_speed);
        dvec3 off = dv3_sub(f->cam_pos, dv3_scale(drop_v, (double)f->time));
        u3f(p, "uBoxOffset", (float)fmod(off.x, box), (float)fmod(off.y, box), (float)fmod(off.z, box));
        u1f(p, "uBox", box);
        vec3 rel_v = v3_sub(dv3_to_v3(drop_v), f->ac_vel);
        u3v(p, "uVel", rel_v);
        u1f(p, "uStreak", 1.f / 60.f);
        u1f(p, "uSnow", snow);
        u1f(p, "uAmount", fmaxf(w->rain, w->snow));
        u1f(p, "uPixelAngle", pixel_angle);
        tex(p, "uProbe", 0, GL_TEXTURE_2D, r->t_probe);
        u3v(p, "uFlashCol", v3_scale(v3(0.7f, 0.75f, 1.f), flash_scene * 0.3f));
        glUniform4fv(loc(p, "uPointPos"), 4, pp);
        glUniform3fv(loc(p, "uPointCol"), 4, pc);
        glDrawArraysInstanced(GL_TRIANGLE_STRIP, 0, 4, snow > 0.5f ? RAIN_DROPS / 2 : RAIN_DROPS);
    }
    /* the lightning channel */
    {
        static float bolt[BOLT_MAX * 8];
        int n = build_bolt(f, bolt);
        if (n > 0) {
            unsigned p = r->p_bolt;
            glBlendFunc(GL_ONE, GL_ONE);
            glDisable(GL_DEPTH_TEST);
            glUseProgram(p);
            um4(p, "uViewProj", &vp_terr);
            u1f(p, "uFlash", fminf(f->ws->flash, 1.5f) * fmaxf(L.pre, 0.35f));
            glBindBuffer(GL_ARRAY_BUFFER, r->bolt_vbo);
            glBufferData(GL_ARRAY_BUFFER, (GLsizeiptr)(sizeof(float) * 8 * (size_t)n), bolt, GL_STREAM_DRAW);
            glEnableVertexAttribArray(0);
            glVertexAttribPointer(0, 4, GL_FLOAT, GL_FALSE, 32, (void *)0);
            glVertexAttribDivisor(0, 1);
            glEnableVertexAttribArray(1);
            glVertexAttribPointer(1, 4, GL_FLOAT, GL_FALSE, 32, (void *)16);
            glVertexAttribDivisor(1, 1);
            for (int pass = 0; pass < 2; ++pass) {
                u1f(p, "uGlow", pass == 0 ? 1.f : 0.f);
                glDrawArraysInstanced(GL_TRIANGLE_STRIP, 0, 4, n);
            }
            glVertexAttribDivisor(0, 0);
            glVertexAttribDivisor(1, 0);
            glDisableVertexAttribArray(0);
            glDisableVertexAttribArray(1);
            glBindBuffer(GL_ARRAY_BUFFER, 0);
            glEnable(GL_DEPTH_TEST);
        }
    }
    /* contrails */
    if (f->trails && f->trails->count > 1) {
        static float tv[TRAIL_SAMPLES * TRAIL_ENGINES * 10];
        const Trails *t = f->trails;
        int n = 0;
        for (int e = 0; e < TRAIL_ENGINES; ++e) {
            /* newest to oldest; the first segment starts at the nozzle itself */
            vec3 prev = v3_add(ac_rel, basis_apply(f->ac_basis, trail_nozzle[e]));
            float prev_age = 0.f;
            for (int k = 0; k < t->count; ++k) {
                int i = (t->head - 1 - k + TRAIL_SAMPLES * 2) % TRAIL_SAMPLES;
                dvec3 wpos = dv3_add(t->air[i][e], f->wind_off);
                vec3 cur = dv3_to_v3(dv3_sub(wpos, f->cam_pos));
                float age = f->time - t->born[i];
                /* condensation starts a few tens of metres back, the trail
                 * spreads with age and thins out over a minute */
                float op = t->strength[i] * smoothstepf(0.08f, 0.6f, age) * (1.f - smoothstepf(20.f, 70.f, age));
                float wd = 0.9f + sqrtf(age) * 1.3f;
                if (op > 0.003f) {
                    float *o = tv + n * 10;
                    o[0] = prev.x; o[1] = prev.y; o[2] = prev.z; o[3] = wd;
                    o[4] = cur.x; o[5] = cur.y; o[6] = cur.z; o[7] = op * 0.9f;
                    o[8] = prev_age; o[9] = age;
                    n++;
                }
                prev = cur;
                prev_age = age;
            }
        }
        if (n > 0) {
            unsigned p = r->p_trail;
            glBlendFunc(GL_ONE, GL_ONE_MINUS_SRC_ALPHA);
            glUseProgram(p);
            um4(p, "uViewProj", &vp_ac);
            tex(p, "uProbe", 0, GL_TEXTURE_2D, r->t_probe);
            u3v(p, "uLightDir", L.key_dir);
            u1f(p, "uTime", f->time);
            glBindBuffer(GL_ARRAY_BUFFER, r->trail_vbo);
            glBufferData(GL_ARRAY_BUFFER, (GLsizeiptr)(sizeof(float) * 10 * (size_t)n), tv, GL_STREAM_DRAW);
            for (int a = 0; a < 3; ++a) {
                glEnableVertexAttribArray((GLuint)a);
                glVertexAttribDivisor((GLuint)a, 1);
            }
            glVertexAttribPointer(0, 4, GL_FLOAT, GL_FALSE, 40, (void *)0);
            glVertexAttribPointer(1, 4, GL_FLOAT, GL_FALSE, 40, (void *)16);
            glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, 40, (void *)32);
            glDrawArraysInstanced(GL_TRIANGLE_STRIP, 0, 4, n);
            for (int a = 0; a < 3; ++a) {
                glVertexAttribDivisor((GLuint)a, 0);
                glDisableVertexAttribArray((GLuint)a);
            }
            glBindBuffer(GL_ARRAY_BUFFER, 0);
        }
    }
    /* the navigation lights */
    if (f->nav_lights) {
        unsigned p = r->p_lights;
        glBlendFunc(GL_ONE, GL_ONE);
        glUseProgram(p);
        um4(p, "uViewProj", &vp_ac);
        float lp[32], lc[32];
        for (int i = 0; i < 7; ++i) {
            lp[i * 4] = nl[i].pos.x; lp[i * 4 + 1] = nl[i].pos.y; lp[i * 4 + 2] = nl[i].pos.z;
            lp[i * 4 + 3] = nl[i].size;
            lc[i * 4] = nl[i].col.x * 60.f; lc[i * 4 + 1] = nl[i].col.y * 60.f; lc[i * 4 + 2] = nl[i].col.z * 60.f;
            lc[i * 4 + 3] = nl[i].on;
        }
        glUniform4fv(loc(p, "uLightPos"), 7, lp);
        glUniform4fv(loc(p, "uLightCol"), 7, lc);
        u2f(p, "uRes", (float)r->w, (float)r->h);
        glDrawArraysInstanced(GL_TRIANGLE_STRIP, 0, 4, 7);
    }
    glDisable(GL_BLEND);
    glDepthMask(GL_TRUE);
    glDisable(GL_DEPTH_TEST);

    /* --- 8. the eye, the glow, the picture ----------------------------------------- */
    glBindFramebuffer(GL_FRAMEBUFFER, r->f_lum);
    glViewport(0, 0, LUM_N, LUM_N);
    glUseProgram(r->p_lum);
    tex(r->p_lum, "uTex", 0, GL_TEXTURE_2D, r->t_comp);
    draw_fullscreen();
    glBindTexture(GL_TEXTURE_2D, r->t_lum);
    glGenerateMipmap(GL_TEXTURE_2D);
    int ai = r->adapt_idx, ao = ai ^ 1;
    glBindFramebuffer(GL_FRAMEBUFFER, r->f_adapt[ao]);
    glViewport(0, 0, 1, 1);
    glUseProgram(r->p_adapt);
    tex(r->p_adapt, "uLum", 0, GL_TEXTURE_2D, r->t_lum);
    tex(r->p_adapt, "uPrev", 1, GL_TEXTURE_2D, r->t_adapt[ai]);
    u1f(r->p_adapt, "uDt", f->dt);
    u1f(r->p_adapt, "uLevels", (float)r->lum_levels);
    u1f(r->p_adapt, "uReset", r->adapt_reset ? 1.f : 0.f);
    draw_fullscreen();
    r->adapt_reset = 0;
    r->adapt_idx = ao;

    if (f->bloom > 0.f) {
        glViewport(0, 0, r->bloom_w, r->bloom_h);
        glBindFramebuffer(GL_FRAMEBUFFER, r->f_bloom[0]);
        glUseProgram(r->p_bright);
        tex(r->p_bright, "uTex", 0, GL_TEXTURE_2D, r->t_comp);
        u1f(r->p_bright, "uThreshold", 5.0f);
        u1f(r->p_bright, "uKnee", 3.0f);
        draw_fullscreen();
        glUseProgram(r->p_blur);
        u1i(r->p_blur, "uTex", 0);
        for (int pass = 0; pass < 3; ++pass) {
            float rad = (pass == 0 ? 1.5f : (pass == 1 ? 4.f : 9.f));
            glBindFramebuffer(GL_FRAMEBUFFER, r->f_bloom[1]);
            glBindTexture(GL_TEXTURE_2D, r->t_bloom[0]);
            glUniform2f(loc(r->p_blur, "uStep"), rad / (float)r->bloom_w, 0.f);
            draw_fullscreen();
            glBindFramebuffer(GL_FRAMEBUFFER, r->f_bloom[0]);
            glBindTexture(GL_TEXTURE_2D, r->t_bloom[1]);
            glUniform2f(loc(r->p_blur, "uStep"), 0.f, rad / (float)r->bloom_h);
            draw_fullscreen();
        }
    }

    /* the tone-mapped picture goes to a texture the size of the window, for
     * the last pass */
    if (r->ldr_w != r->width || r->ldr_h != r->height || !r->f_ldr) {
        del_tex(&r->t_ldr); del_fbo(&r->f_ldr);
        r->t_ldr = make_tex2d(r->width, r->height, GL_RGBA8, GL_RGBA, GL_UNSIGNED_BYTE, GL_LINEAR, GL_CLAMP_TO_EDGE);
        r->f_ldr = make_fbo(r->t_ldr, 0);
        r->ldr_w = r->width; r->ldr_h = r->height;
    }
    glBindFramebuffer(GL_FRAMEBUFFER, r->f_ldr);
    glViewport(0, 0, r->width, r->height);
    {
        unsigned p = r->p_final;
        glUseProgram(p);
        tex(p, "uHDR", 0, GL_TEXTURE_2D, r->t_comp);
        tex(p, "uBloom", 1, GL_TEXTURE_2D, r->t_bloom[0]);
        tex(p, "uAdapt", 2, GL_TEXTURE_2D, r->t_adapt[r->adapt_idx]);
        tex(p, "uProbe", 3, GL_TEXTURE_2D, r->t_probe);
        u1f(p, "uBloomAmt", f->bloom > 0.f ? f->bloom * 0.07f : 0.f);
        u1f(p, "uKey", 0.2f);
        u1f(p, "uExpBias", w->exposure);
        u1f(p, "uNight", L.night);
        float su = 0.f, sv = 0.f;
        int front = render_project_dir(f, aspect, L.sun_dir, &su, &sv) && w->sun_elev > -1.f;
        u3f(p, "uSun", su, sv, front ? 1.f : 0.f);
        u3v(p, "uSunLum", v3_scale(L.sun_illum, 800.f));
        u1f(p, "uLens", f->lens ? 1.f : 0.f);
        u1f(p, "uDrops", f->cam_on_airframe && !f->cam_external ? fmaxf(w->rain, w->snow * 0.3f) : 0.f);
        /* water on the lens runs away from the direction of flight */
        {
            vec3 fwd = v3_scale(f->ac_basis.z, -1.f);
            float fx = v3_dot(fwd, f->cam_basis.x), fy = v3_dot(fwd, f->cam_basis.y);
            float fz = -v3_dot(fwd, f->cam_basis.z);
            float lx = -fx, ly = -fy - 0.2f;
            if (fz > 0.5f) { lx = 0.f; ly = -0.3f; }   /* looking ahead: it streams out and down */
            float l = sqrtf(lx * lx + ly * ly) + 1e-4f;
            u2f(p, "uFlow", lx / l, ly / l);
        }
        u1f(p, "uTime", f->time);
        u2f(p, "uRes", (float)r->width, (float)r->height);
        draw_fullscreen();
    }
    /* grain and the fade, onto the screen */
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    glViewport(0, 0, r->width, r->height);
    {
        unsigned p = r->p_present;
        glUseProgram(p);
        tex(p, "uLDR", 0, GL_TEXTURE_2D, r->t_ldr);
        u1f(p, "uTime", f->time);
        u1f(p, "uNight", L.night);
        u1f(p, "uFade", f->fade);
        draw_fullscreen();
    }
    gpu_timer_end(r);
#ifdef MR_DEBUG
    gl_check("render_frame");
#endif
}

void render_shutdown(Renderer *r) {
    unsigned progs[] = { r->p_trans, r->p_multi, r->p_skyview, r->p_aerial, r->p_noise, r->p_weather,
                         r->p_cshadow, r->p_probe, r->p_sky, r->p_clouds, r->p_composite, r->p_lum,
                         r->p_adapt, r->p_bright, r->p_blur, r->p_blit, r->p_final, r->p_terrain,
                         r->p_aircraft, r->p_shadow, r->p_precip, r->p_bolt, r->p_lights, r->p_trail, r->p_cloudtaa,
                         r->p_present, r->p_resolve };
    for (size_t i = 0; i < sizeof progs / sizeof *progs; ++i) if (progs[i]) glDeleteProgram(progs[i]);
    model_free(&r->model);
    unsigned texs[] = { r->t_trans, r->t_multi, r->t_skyview, r->t_aerial, r->t_aerialT, r->t_noise_base,
                        r->t_noise_detail, r->t_weather, r->t_cshadow, r->t_probe, r->t_clouds, r->t_shadow,
                        r->t_scene, r->t_dist, r->t_comp, r->t_lum, r->t_adapt[0], r->t_adapt[1],
                        r->t_bloom[0], r->t_bloom[1], r->t_ldr, r->t_ms_color, r->t_ms_dist };
    for (size_t i = 0; i < sizeof texs / sizeof *texs; ++i) if (texs[i]) glDeleteTextures(1, &texs[i]);
    unsigned fbos[] = { r->f_trans, r->f_multi, r->f_skyview, r->f_aerial, r->f_weather, r->f_cshadow,
                        r->f_probe, r->f_clouds, r->f_shadow, r->f_scene, r->f_comp, r->f_lum,
                        r->f_adapt[0], r->f_adapt[1], r->f_bloom[0], r->f_bloom[1], r->f_ldr, r->f_ms };
    for (size_t i = 0; i < sizeof fbos / sizeof *fbos; ++i) if (fbos[i]) glDeleteFramebuffers(1, &fbos[i]);
    if (r->rb_depth) glDeleteRenderbuffers(1, &r->rb_depth);
    if (r->rb_ms_depth) glDeleteRenderbuffers(1, &r->rb_ms_depth);
    if (r->terr_vbo) glDeleteBuffers(1, &r->terr_vbo);
    if (r->terr_ibo) glDeleteBuffers(1, &r->terr_ibo);
    if (r->terr_vao) glDeleteVertexArrays(1, &r->terr_vao);
    if (r->bolt_vbo) glDeleteBuffers(1, &r->bolt_vbo);
    if (r->trail_vbo) glDeleteBuffers(1, &r->trail_vbo);
    if (r->vao) glDeleteVertexArrays(1, &r->vao);
    if (r->gpu_query[0]) glDeleteQueries(3, r->gpu_query);
    memset(r, 0, sizeof *r);
}

unsigned char *render_read_rgba(const Renderer *r, int *wo, int *ho) {
    int w = r->width, h = r->height;
    unsigned char *px = malloc((size_t)w * h * 4);
    if (!px) return NULL;
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    glPixelStorei(GL_PACK_ALIGNMENT, 1);
    glReadPixels(0, 0, w, h, GL_RGBA, GL_UNSIGNED_BYTE, px);
    for (int y = 0; y < h / 2; ++y) {
        unsigned char *a = px + (size_t)y * w * 4, *b = px + (size_t)(h - 1 - y) * w * 4;
        for (int i = 0; i < w * 4; ++i) { unsigned char t = a[i]; a[i] = b[i]; b[i] = t; }
    }
    for (size_t i = 3; i < (size_t)w * h * 4; i += 4) px[i] = 255;
    *wo = w; *ho = h;
    return px;
}

int render_write_png(const char *path, const unsigned char *rgba, int w, int h) {
    return stbi_write_png(path, w, h, 4, rgba, w * 4);
}

int render_dump_png(const Renderer *r, const char *path) {
    int w = r->width, h = r->height;
    unsigned char *px = malloc((size_t)w * h * 4);
    if (!px) return 0;
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    glPixelStorei(GL_PACK_ALIGNMENT, 1);
    glReadPixels(0, 0, w, h, GL_RGBA, GL_UNSIGNED_BYTE, px);
    for (int y = 0; y < h / 2; ++y) {
        unsigned char *a = px + (size_t)y * w * 4, *b = px + (size_t)(h - 1 - y) * w * 4;
        for (int i = 0; i < w * 4; ++i) { unsigned char t = a[i]; a[i] = b[i]; b[i] = t; }
    }
    for (size_t i = 3; i < (size_t)w * h * 4; i += 4) px[i] = 255;
    int ok = stbi_write_png(path, w, h, 4, px, w * 4);
    free(px);
    return ok;
}
